"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import './TextLayer.css'
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import { motion, AnimatePresence } from "framer-motion";

type Props = {
  children: any;
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html>
      <head />
      <body
        className={`${poppins.className} backgroundImage text-white min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
