import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer'

const poppins = Poppins({  
  weight:['400'],
  subsets:[ "latin"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body  className={`${poppins.className} backgroundImage `}>
        <Navbar/>
        {children}
          
        <Footer/>
        </body>
    </html>
  )
}
